style_edition = "2024"

newline_style = "Unix"
use_field_init_shorthand = true
use_small_heuristics = "Max"
match_block_trailing_comma = true

unstable_features = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
format_code_in_doc_comments = true
overflow_delimited_expr = true
match_arm_blocks = false
enum_discrim_align_threshold = 20
struct_field_align_threshold = 20
